Repository prgrms-be-devcourse/NBE4-5-1-Team10, pull requests merged in 2025-02, with the labels that each got.

#30 Feat/member/#9
  .gitignore
  .idea/dataSources/259c9f0f-ecad-4597-ae86-46d4cb4540df.xml
  backend/.gitignore
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/controller/LoginController.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/dto/JoinDTO.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/dto/UserJoinRequest.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/dto/UserResponse.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/entity/Users.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/repository/UserRepository.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/service/LoginService.java
  backend/src/main/java/nbe341team10/coffeeproject/global/config/SecurityConfig.java
  backend/src/test/java/nbe341team10/coffeeproject/CoffeeprojectApplicationTests.java
  backend/src/test/java/nbe341team10/coffeeproject/user/UserTest.java
Labels: ♻️ refactor, BE

#36 Feat/member/#9 temp
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/entity/Users.java
Labels: ⛔️ bug

#26 Feat/product/#5 Product Detail API
  backend/src/main/java/nbe341team10/coffeeproject/domain/product/controller/ApiV1ProductController.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/product/dto/ProductGetItemDto.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/product/dto/ProductGetItemsDto.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/product/service/ProductService.java
  backend/src/test/java/nbe341team10/coffeeproject/product/ApiV1ProductControllerTest.java
Labels: ✨ feature, BE

#47 Feat/user/#15
  backend/build.gradle
  backend/src/main/java/nbe341team10/coffeeproject/domain/jwt/CustomLoginFilter.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/jwt/JWTFilter.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/jwt/JWTUtil.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/controller/LoginController.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/controller/home.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/dto/CustomUserDetails.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/entity/Refresh.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/repository/RefreshRepository.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/repository/UserRepository.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/service/CustomUserService.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/service/LoginService.java
  backend/src/main/java/nbe341team10/coffeeproject/global/config/CorsMvcConfig.java
  backend/src/main/java/nbe341team10/coffeeproject/global/config/SecurityConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/java/nbe341team10/coffeeproject/ApiV1CartControllerTest.java
  backend/src/test/java/nbe341team10/coffeeproject/user/ApiV1LoginTest.java
  backend/src/test/java/nbe341team10/coffeeproject/user/UserTest.java
Labels: ✨ feature, BE

#61 Fix/Cart/#58 Add Authorization in Cart Domain
  backend/src/main/java/nbe341team10/coffeeproject/domain/cart/controller/ApiV1CartController.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/cart/service/CartService.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/jwt/CustomLoginFilter.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/jwt/JWTFilter.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/jwt/JWTUtil.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/dto/CustomUserDetails.java
  backend/src/main/java/nbe341team10/coffeeproject/domain/user/service/LoginService.java
  backend/src/main/java/nbe341team10/coffeeproject/global/Rq.java
  backend/src/main/java/nbe341team10/coffeeproject/global/config/SecurityConfig.java
  backend/src/test/java/nbe341team10/coffeeproject/ApiV1CartControllerTest.java
  backend/src/test/java/nbe341team10/coffeeproject/cart/ApiV1CartControllerTest.java
  backend/src/test/java/nbe341team10/coffeeproject/product/ApiV1ProductControllerTest.java
Labels: ✨ feature, BE

#72 Feat/user/#16: Admin access Test
  backend/src/test/java/nbe341team10/coffeeproject/user/ApiV1LoginTest.java
Labels: ✅ test

#86 docs:요구사항 명세서, 서비스 소개
  README.md
  frontend/frontend@0.1.0
  frontend/next
Labels: 📋 docs

#90 feat/join/#70 회원가입, 로그아웃
  .vscode/launch.json
  backend/src/main/resources/application.yml
  frontend/src/app/api/cart/route.ts
  frontend/src/app/api/user/join/route.ts
  frontend/src/app/api/user/logout/route.ts
  frontend/src/app/client-layout.tsx
  frontend/src/app/client-page.tsx
  frontend/src/app/user/join/client-page.tsx
  frontend/src/app/user/join/page.tsx
  frontend/src/app/user/logout/client-page.tsx
  frontend/src/app/user/logout/page.tsx
  frontend/src/stores/auth/auth-store.tsx
Labels: ✨ feature, FE
